baseURL = "/"
languageCode = "en-us"
title = "Goose Exteriors"
theme = ""
enableRobotsTXT = true

[params]
  description = "Pressure Washing You Can Trust – Located in Media, PA"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 3

  [[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    url = "/gallery/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5
